### ISSUE TITLE
Add code of conduct document (first-timers-only)

### ISSUE THREAD

**Issue by TalAter** [DAVFoundation/ride-hailing-app#2]
## first-timers-only

This issue is tagged :octocat: **first-timers-only**. It is only for people who have never contributed to open source before, and are looking for an easy way take their first steps.

Consider this your chance to dip your toe into the world of open-source, and get some bragging rights for helping make drones fly, cars find charging stations, and people and goods get from place to place.

Find more **first-timers-only** issues [here](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+archived%3Afalse+label%3A%22good+first+issue%22+user%3ADAVFoundation+).

Thank you for your help :heart:

## What is this project? 

DAV (Decentralized Autonomous Vehicles) is a non-profit foundation working to build an open-source infrastructure for autonomous vehicles (cars, drones, trucks, robots, boats, and all the service providers around them) to communicate and transact with each other over blockchain.

As an organization that believes in building a large community of open-source contributors, we often create issues like this one to help people take their first few steps into the world of open source.

### Ride Hailing App

The DAV project you are looking at is a decentralized ride hailing app. It is decentralized app connecting drivers and passengers, directly without a middleman.

## How you can help

To help create an open and welcoming environment, we would like to have a [code of conduct](https://opensource.guide/code-of-conduct/) document as part of this project.

Please add a file called `code_of_conduct.md` to the root of the project. This file should be based on the [Contributor Covenant Code of Conduct](https://contributor-covenant.org/version/1/4/code_of_conduct.md). This document requires an email address in it. Please enter `tal@dav.network`

### Contributing to ride hailing app

- [ ] Make sure this issue is labeled up-for-grabs and not labeled claimed, to verify no one else is working on it.
- [ ] Comment in this issue that you would like to do it.
- [ ] Open the [ride hailing app GitHub page](https://github.com/DAVFoundation/ride-hailing-app) and click the ★ Star and then ⑂ Fork buttons.
- [ ] Clone a copy to your local machine with `$ git clone git@github.com:YOUR-GITHUB-USER-NAME/ride-hailing-app.git`
- [ ] **Add the file**
- [ ] Commit your changes and push your local changes back to github with `$ git push -u origin master`
- [ ] Visit your fork on GitHub.com ([https://github.com/YOUR-USER-NAME/ride-hailing-app](https://github.com/YOUR-USER-NAME/ride-hailing-app)) and create a pull request for your changes.
- [ ] Make sure your pull request describes exactly what you changed and references this issue (include the issue number in the title like this: `#1`)
- [ ] Please do not fix more than one issue at a time. Your pull request should only fix what is described in this issue.

### Asking for help

We appreciate your effort in taking the time to work on this issue and help out the open source community and the foundation. If you need any help, feel free to ask below or in our [gitter channel](https://gitter.im/DAVFoundation/DAV-Contributors). We are always happy to help 😄

We sometimes feature the work done by the community on our website. If you would like your GitHub user excluded from that, please email tal@dav.network

**Comment by TalAter** [comment]
Thank you for the help @Aliciawyse 

I saw your GitHub activity board is already quite green 👏... would you be interested in taking some meatier issues?
For example https://github.com/DAVFoundation/dav-js/issues/18 is for testing some of the code that will control the autonomous boat we are building with the California Maritime University... it's a fun chance to get involved with open source code that will control a marine research vessel.

![n3m0_sailing](https://user-images.githubusercontent.com/926653/44045769-405c4404-9f32-11e8-86d1-a3e15f08e35b.gif)

![n3m0_open](https://user-images.githubusercontent.com/926653/44045787-52de3786-9f32-11e8-9e1b-5773b7abc7ea.jpg)

**Comment by Aliciawyse** [comment]
Hey @TalAter Yeah, you know what, I'd love to give DAVFoundation/dav-js#18 a shot! Thanks!
